"use client";

import React, { useState, useCallback } from "react";
import { useChat } from "ai/react"; // Ensure this is the correct import for your SDK
import TimeSelector from "../components/TimeSelector";
import FoodTypeSelector from "../components/FoodTypeSelector";
import DietaryRestrictionsSelector from "../components/DietaryRestrictionsSelector";
import ReligiousDietsSelector from "../components/ReligiousDietsSelector";
import Image from "next/image"; // Import the Next.js Image component

// Define the type for messages
interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
}

export default function Chat() {
  const { error, messages, isLoading, setInput, handleSubmit, reload, stop } =
    useChat({
      keepLastMessageOnError: true,
    });

  const [selectedTime, setSelectedTime] = useState<string | null>(null);
  const [selectedFoodType, setSelectedFoodType] = useState<string | null>(null);
  const [selectedDietaryRestrictions, setSelectedDietaryRestrictions] =
    useState<string[]>([]);
  const [selectedReligiousDiets, setSelectedReligiousDiets] = useState<
    string[]
  >([]);
  const [recipeImage, setRecipeImage] = useState<string | null>(null);

  const validateSelections = useCallback(() => {
    if (!selectedTime || !selectedFoodType) {
      alert(
        "Por favor selecciona al menos un tiempo estimado y la comida que te gustaría comer."
      );
      return false;
    }

    if (
      (selectedDietaryRestrictions.includes("Ninguna") &&
        selectedDietaryRestrictions.length > 1) ||
      (selectedReligiousDiets.includes("Ninguna") &&
        selectedReligiousDiets.length > 1)
    ) {
      alert(
        'No puedes seleccionar la opción: "Ninguna" con otras restricciones dietéticas o dietas religiosas.'
      );
      return false;
    }

    return true;
  }, [
    selectedTime,
    selectedFoodType,
    selectedDietaryRestrictions,
    selectedReligiousDiets,
  ]);

  const onSubmit = useCallback(async () => {
    // Validate selections first
    const isValid = validateSelections();
    if (!isValid) {
      return; // Exit if validation fails
    }

    // Create prompt only if validation succeeds
    const prompt = `Sugiera una receta con los siguientes criterios:
      1. **Tiempo:** ${selectedTime},
      2. **Tipo de comida:** ${selectedFoodType},
      ${
        selectedDietaryRestrictions.length > 0
          ? `3. **Restricción alimentaria:** ${selectedDietaryRestrictions.join(
              ", "
            )},`
          : ""
      }
      ${
        selectedReligiousDiets.length > 0
          ? `4. **Restricción religiosa:** ${selectedReligiousDiets.join(
              ", "
            )},`
          : ""
      }
      Por favor, proporcione una receta única que no haya generado anteriormente, que se ajuste a los criterios mencionados anteriormente. Incluya lo siguiente en su respuesta:
      - **Nombre de la receta**
      - **Lista de ingredientes**
      - **Instrucciones paso a paso detalladas**
      - **Preparación y tiempo de cocción**
      
      Asegurese de que los titulos son exactos a los anteriormente proporcionados. Asegurese de que la receta es clara. Asegurese de que los ingredientes están en medición imperial y que sea fácil de seguir. Gracias!`;

    setInput(prompt);
    await handleSubmit(); // Trigger API call here
  }, [
    setInput,
    handleSubmit,
    validateSelections,
    selectedTime,
    selectedFoodType,
    selectedDietaryRestrictions,
    selectedReligiousDiets,
  ]);

  const extractRecipeDetails = (content: string) => {
    // Use regular expressions to extract the recipe name and ingredients from the content
    const nameMatch = content.match(/(Nombre de la receta|Receta):\s*(.*)/i);
    const ingredientsMatch = content.match(
      /(Lista de ingredientes|Ingredientes):\s*([\s\S]*?)\n\n/i
    );

    const recipeName = nameMatch ? nameMatch[1].trim() : "Receta desconocida";
    const ingredients = ingredientsMatch ? ingredientsMatch[1].trim() : "";

    return { recipeName, ingredients };
  };

  const onGenerateImage = useCallback(async () => {
    // Find the most recent recipe content generated by the AI
    const recipeMessage = messages.find((m) => m.role === "assistant");

    if (!recipeMessage) {
      alert("Primero sugiere una receta antes de generar la imagen.");
      return;
    }

    const { recipeName, ingredients } = extractRecipeDetails(
      recipeMessage.content
    );

    try {
      const imageResponse = await fetch("/api/generateImage", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          description: `Create an image of a dish named "${recipeName}" using the following ingredients: ${ingredients}.`,
        }),
      });

      if (!imageResponse.ok) {
        throw new Error(`HTTP error! status: ${imageResponse.status}`);
      }

      const imageData = await imageResponse.json();
      if (imageData.imageUrl) {
        setRecipeImage(imageData.imageUrl); // Set the image URL in state
      } else {
        console.error("Failed to fetch image:", imageData.message);
      }
    } catch (error) {
      console.error("Error fetching image:", error);
    }
  }, [messages]);

  const onReset = useCallback(() => {
    setSelectedTime(null);
    setSelectedFoodType(null);
    setSelectedDietaryRestrictions([]);
    setSelectedReligiousDiets([]);
    setRecipeImage(null);
    setInput("");
    window.location.reload();
  }, [setInput]);

  return (
    <div className="flex flex-col items-center w-full max-w-2xl py-24 mx-auto">
      <header className="mb-6 text-center">
        <h1 className="text-3xl font-bold">Recetario Inteligente</h1>
      </header>
      <TimeSelector onSelectTime={setSelectedTime} />
      <FoodTypeSelector onSelectFoodType={setSelectedFoodType} />
      <DietaryRestrictionsSelector
        onSelectRestriction={setSelectedDietaryRestrictions}
      />
      <ReligiousDietsSelector onSelectRestriction={setSelectedReligiousDiets} />

      <div className="flex w-full space-x-2 mt-5">
        <button type="button" onClick={onSubmit} className="w-full btn">
          Sugerir Receta
        </button>

        <button type="button" onClick={onGenerateImage} className="w-full btn">
          Generar Imagen
        </button>

        <button type="button" onClick={onReset} className="w-full btn">
          Iniciar Nuevamente
        </button>
      </div>

      {isLoading && (
        <div className="mt-4 text-gray-500">
          <div>Loading...</div>
          <button
            type="button"
            className="px-4 py-2 mt-4 text-blue-500 border border-blue-500 rounded-md"
            onClick={stop}
          >
            Stop
          </button>
        </div>
      )}

      {error && (
        <div className="mt-4">
          <div className="text-red-500">Un error ha ocurrido.</div>
          <button
            type="button"
            className="px-4 py-2 mt-4 text-blue-500 border border-blue-500 rounded-md"
            onClick={() => reload()}
          >
            Retry
          </button>
        </div>
      )}

      <div className="mt-4 p-4 bg-white rounded shadow w-full">
        {messages
          .filter((m) => m.role === "assistant")
          .map((m) => (
            <div key={m.id} className="whitespace-pre-wrap mb-6">
              <p className="text-lg font-medium mb-2">Platillo recomendado:</p>
              <p className="p-4 bg-gray-100 rounded-md">{m.content}</p>
            </div>
          ))}
        {recipeImage && (
          <div className="mt-4">
            <p className="text-lg font-medium mb-2">Imagen del platillo:</p>
            <Image
              src={recipeImage}
              alt="Generated dish"
              width={256}
              height={256}
              className="w-full rounded-md"
            />
          </div>
        )}
      </div>

      <footer className="mt-12 text-center text-gray-500">
        © {new Date().getFullYear()}{" "}
        <a href="https://www.camilooviedo.com/" className="hover:underline">
          Camilo Oviedo
        </a>
        . Almost all Rights Reserved.
      </footer>
    </div>
  );
}
